---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: ubuntu-vm-2
  namespace: default
  labels:
    app: ubuntu-vm
spec:
  runStrategy: Always
  template:
    metadata:
      labels:
        kubevirt.io/domain: ubuntu-vm-2
    spec:
      domain:
        cpu:
          cores: 1
        memory:
          guest: 512Mi
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
        resources:
          requests:
            memory: 512Mi
            cpu: "1"
      networks:
        - name: default
          pod: {}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: NotIn
                    values:
                      - k3s-master    
      volumes:
        - name: rootdisk
          dataVolume:
            name: ubuntu-vm-2-disk
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              hostname: ubuntu-vm-2
              user: ubuntu
              password: ubuntu123
              chpasswd:
                expire: false
              ssh_pwauth: true
              ssh_authorized_keys:
              # Replace with your own public key (cat ~/.ssh/ansible_id.pub)
                - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDBPCiI6HrfXiRIn9v1X0GJvtIH+tux3LekD+32OhFk1CIYfwzo9fYvNz70//+OyS40PXYChCMa9BrjDMpDgkvfjXvO5JuOG3f6KCuqchAVEID33rNmmx+gkHtqlMQ3Uf5B4HWIN2UJUs2wmBh2hb2LsHpj9FkcChT/nuVnhE356++9nXc31JT5aD4inDdU/FQRWiE7EN/dk+7cmdvNlO7XPpJ9Xm7wNN8l1Vew6e4aepJN4w0UDE78CoHQtRbMYT3dEqEbD5/21KB2gdfJ+7gOvb3B6vhLLOQK+JLxD0u/5b1nUWU5bWO3aUN6GFhLno5No01fbbCcmNHEUdX+e36kqPIrHHLBMfqzo+/Idm6yojKz987uzfLRqumxp3a2iaBjY8N8Kt6giKzIJ46XxA/Dcp8z5AW7XQPjVffP3abHghlxgL8T5yHQx4qgOYOHN0UG/19Fd5xjAkw7riuDNXAA2bHaKjgsWh5W16yplkXIrhQTvWjP6qHk/ydMJavRJmTvra/Hx/5aMD2wn7o6hBgs2r2e+QsD02fYNVe9H0FnG44sI1aqh/VmlYicvXIuipgg74fdzNYX+unM7mlBoB9ogreMam8lt9tzhJZWNkOtK6KtGffbY7bEfFdKBCAXXSvAViBk3qwij8q6zegYfrDxq9llr68tlKZLmCV9ocd8nw== ansible-jumphost
              write_files:
                - path: /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg
                  content: |
                    network: {config: disabled}
                - path: /etc/netplan/99-kubevirt.yaml
                  content: |
                    network:
                      version: 2
                      ethernets:
                        enp1s0:
                          dhcp4: true
                          dhcp6: true
              bootcmd:
                - rm -f /etc/netplan/50-cloud-init.yaml             
  dataVolumeTemplates:
    - metadata:
        name: ubuntu-vm-2-disk
      spec:
        storage:
          accessModes:
            - ReadWriteMany
          resources:
            requests:
              storage: 5Gi
          storageClassName: longhorn
        source:
          http:
            url: "https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-arm64.img"